version: '3.8'

services:
  varuna:
    image: varunapriyas/personal-api:latest
    container_name: Varunapersonal-api-container
    ports:
      - "5004:5000"  
    restart: always

  santhiya:
    image: santhiya55/personal-api:latest
    container_name: sandy-container
    ports:
      - "5005:5000"  
    restart: always
